sudo: required

language: cpp

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - $HOME/docker

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - pwd

script:
  - travis_wait docker pull hnagamin/llvm-3.9:latest
  - docker-compose run workspace make -C /worktree/XcodeMLtoCXX check
