sudo: required

language: cpp

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - pwd
  - docker-compose up -d
  - docker-compose ps

script:
  - docker-compose run workspace make -C /worktree/XcodeMLtoCXX check
