sudo: required
language: cpp
services:
  - docker
before_install:
  - docker pull koyama41/llvm-3.6
script:
  - docker run -v $(pwd):/tree ubuntu:latest /usr/bin/make -C /tree/src
  - docker run -v $(pwd):/tree ubuntu:latest /usr/bin/make -C /tree/XcodeMLtoCXX
  - docker run -v $(pwd):/tree ubuntu:latest /usr/bin/make -C /tree/XcodeMLtoCXX test
