sudo: required

language: cpp

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - pwd
  - docker-compose up -d

script:
  - docker-compose run workspace ls
  - docker-compose run workspace make -C XcodeMLtoCXX check
